DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS game;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,

	coins INTEGER,
	xp INTEGER,
	lvl INTEGER,

	is_admin BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE game (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	creator TEXT NOT NULL,
	game_title TEXT UNIQUE NOT NULL,
	api_key TEXT UNIQUE NOT NULL,
	game_url TEXT UNIQUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (author_id) REFERENCES user (id)
);
